import {Hero} from './hero';

export const HEROES: Hero[] = [
  { id: 1, name:'Iron Man'  },
  { id: 2, name:'Captain America'  },
  { id: 3, name:'Black Widow'  },
  { id: 4, name:'Hulk'  },
  { id: 5, name:'Thor'  },
  { id: 6, name:'Hawkeye'  },
  { id: 7, name:'Spider Man'  },
  { id: 8, name:'Black Panther'  },
  { id: 9, name:'Dr. Strange'  },
  { id: 10, name:'Vision'  },
  { id: 12, name:'Groot'  },
  { id: 13, name:'Rocket Raccoon'  },
  { id: 14, name:'Gamora'  },
  { id: 15, name:'Drax'  },
  { id: 16, name:'Luke Cage'  },
  { id: 17, name:'Daredevil'  },
  { id: 18, name:'Jessica Jones'  },
  { id: 19, name:'Iron Fist'  },
  { id: 20, name:'Rogue'  },
  { id: 21, name:'Cyclops'  },
  { id: 22, name:'Ice Man'  },
  { id: 23, name:'Storm'  },
  { id: 24, name:'Wolverine'  },
  { id: 25, name:'Professor X'  },
  { id: 26, name:'Beast'  },
  { id: 27, name:'Star Lord'  }
];